version: "3.4"
services:
  nitro-node:
    image: offchainlabs/nitro-node:${IMAGE_TAG_NITRO_NODE:-latest}
    restart: on-failure
    stop_grace_period: 5m
    command: >
      nitro-node
      --parent-chain.connection.url="$L1_RPC_URL"
      --http.api=net,web3,eth,debug,trace 
      --http.corsdomain=* 
      --http.addr=0.0.0.0
      --http.vhosts=*
      --init.url="$INIT_URL"
    env_file:
      - .env
    volumes:
      - arbitrum:/home/user/.arbitrum
    ports:
      - ${PORT_NITRO_HTTP:-17001}:8545
      - ${PORT_NITRO_WS:-17002}:8546

volumes:
  arbitrum: